### ISSUE TITLE
Cannot display the app data with the latest Docker image

### ISSUE THREAD

**Issue by codeKonami** [parse-community/parse-dashboard#1383]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X] You're running version >=1.0.23 of Parse Dashboard.

- [X] You're running version >=2.3.2 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Latest Docker image => parseplatform/parse-dashboard:latest
"parse-server": "3.9.0"

#### Steps to reproduce
I'm launching a Docker image with Docker compose with this yml block

```
parse-dashboard:
    image: parseplatform/parse-dashboard
    container_name: parsedashboard
    environment:
      PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: 1
      PARSE_DASHBOARD_CONFIG: '{"apps":[{"appId":"AAA","serverURL":"http://localhost:1337/parse","masterKey":"BBB","appName":"SOMENAME","supportedPushLocales":["fr"]}],"users":[{"user":"user","pass":"pass"}]}'
    ports:
      - '127.0.0.1:4040:4040'
```

It worked perfectly with all the previous versions up to the 2.0.5

#### Logs/Trace
I can login to the app, but then the screen stays completely blank.
I can see a browser JS error in the console. 

```
TypeError: Cannot read property 'then' of undefined
    at t.value (dashboard.bundle.js:95)
    at Io (dashboard.bundle.js:45)
    at $a (dashboard.bundle.js:45)
    at Os (dashboard.bundle.js:45)
    at Nu (dashboard.bundle.js:45)
    at Tu (dashboard.bundle.js:45)
    at Eu (dashboard.bundle.js:45)
    at dashboard.bundle.js:45
    at t.unstable_runWithPriority (dashboard.bundle.js:53)
    at Yi (dashboard.bundle.js:45)
```
