### ISSUE TITLE
parse-server ip is not 'resolved'  in docker compose environment

### ISSUE THREAD

**Issue by ash0080** [parse-community/parse-dashboard#1962]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### UPDATE! [solved]
After looking at the source code, I found the solution.
The dashboard request to the parse-server is actually implemented through XMLHttpRequest, which means it is sent on the browser side.
Therefore, the environment variables here are not resolved by docker internal DNS.
You should use the front-end address directly, which is the host ip

"PARSE_DASHBOARD_SERVER_URL: http://locahost:1337/api" in my case.

### Issue Description

This is an old problem, documented since at least 2018, and although all relevant issues have been closed, the problem has never been addressed.

Refs:
#1383
#835
#785

![Screen Shot 2021-12-14 at 1 12 20 PM](https://user-images.githubusercontent.com/2803210/145939180-3de27aab-30e3-48a7-80dc-8cfa9eaa5d08.png)

### Steps to reproduce

```
version: '3.8'
services:

  mongo:
    image: 'mongo:latest'
    volumes:
      - './mongo/db:/data/db'
    environment:
      - blahhhh
    ports:
      - 26000:27017

  parse:
    image: 'parseplatform/parse-server:latest'
    environment:
      - PARSE_SERVER_MOUNT_PATH=/api
      - blahhhh
    ports:
      - '1337:1337'
    depends_on:
      - mongo

  parse-dashboard:
    image: 'parseplatform/parse-dashboard'
    ports:
      - '4040:4040'
    environment:
      - PARSE_DASHBOARD_SERVER_URL: http://parse:1337/api
      - blahhhh
```

### Actual Outcome

Some say it's a docker bug, others say it's an environment variable configuration problem, 
But in fact, this is an issue in the parse-dashboard itself.

```
// nslookup in the parse-dashboard container
$ nslookup parse
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:

Non-authoritative answer:
Name:	parse
Address: 172.21.0.3
```

```
// docker network inspect
...
"Containers": {
            "55d33bbf98895b0ad3234d4d65f36eac2c443f8ac44e562a2175e4913cc2a4d0": {
                "Name": "docker_parse-dashboard_1",
                "EndpointID": "024cacf1ff44212b746bee860785d3e1366a5b2afee9cf7cd4503abfcd8d8129",
                "MacAddress": "02:42:ac:15:00:04",
                "IPv4Address": "172.21.0.4/16",
                "IPv6Address": ""
            },
            "869a55ab0fe1167e89fea9edf1716d74ac042ea392ecefd2b42e036f9c53a247": {
                "Name": "docker_parse_1",
                "EndpointID": "73abe289c748086379c23c9b8d3cf39b0897bdcfbb3c7bcbfbebd20d6c04f640",
                "MacAddress": "02:42:ac:15:00:03",
                "IPv4Address": "172.21.0.3/16",
                "IPv6Address": ""
            },
            "8e41915493d7cae31cbec794f1424f1ce39ba03a780358c0635d03c8e3ede67a": {
                "Name": "docker_mongo_1",
                "EndpointID": "3bb92adcbf0096951077ca5b406ddfb306942468b35f08f33f62e33639f3a8d5",
                "MacAddress": "02:42:ac:15:00:02",
                "IPv4Address": "172.21.0.2/16",
                "IPv6Address": ""
            }
        },
```
see?  docker is resolving the parse container ip correctly, but for unknown reasons, the literal value of the environment variable ends up being used in parse-dashboard. 

### Expected Outcome

Default docker DNS resolve feature

### Environment

Docker Desktop for Mac
Version 4.3.1 (72247)
Engine: 20.10.11
Compose: 1.29.2

```
       Container                    Repository              Tag       Image Id       Size  
-------------------------------------------------------------------------------------------
docker_mongo_1             mongo                           latest   ccf4b4ee3bee   684.9 MB
docker_parse-dashboard_1   parseplatform/parse-dashboard   latest   4cf28bc4ebe1   287.7 MB
docker_parse_1             parseplatform/parse-server      latest   ee3048330ece   224.5 MB
```
