### ISSUE TITLE
Parse dashboard with docker-compose stuck

### ISSUE THREAD

**Issue by ranhsd** [parse-community/parse-dashboard#826]
running version >=1.1.2 of Parse Dashboard.

 running version >=2.7.1 of Parse Server.

#### Environment Setup

Docker-compose with 

- parse server image

- mongoDB image

- Parse dashboard image

I am running parse-dashboard with parse-server and MongoDB using docker-compose.
Everything works well with parse dashboard until i am trying to access the Push page. 
When i'm trying to do that the page is getting stuck. (please see image below)

<img width="810" alt="screen shot 2017-12-24 at 8 57 38" src="https://user-images.githubusercontent.com/3685671/34324836-8fc001fe-e888-11e7-8f7e-37619e394798.png">

If i am trying to run with without docker-compose (via parse-dashboard global command) everything works well.

This is my docker-compose file:

```
version: "2"
services:
  # NODEJS Application server image
  app:
    build: ./app
    command: nodemon -L --delay 2 --debug /my-server/node_modules/.bin/parse-server -- /my-server/config/local-server-config.json
    container_name: my-server
    volumes:
      - ./app:/my-server/
      - /my-server/node_modules
    ports:
      - "1337:1337"
      - "5858:5858"
    links:
      - mongo
   
  dashboard:
    image: parseplatform/parse-dashboard:latest
    volumes:
      - ./dashboard/dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json   
    environment:
      PORT: 4040
      PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: 1
      ALLOW_INSECURE_HTTP: 1
      

    ports:
      - "4040:4040"

  # MongoDB image config 
  mongo:
    image: mongo
    container_name: my-mongo
    ports: 
    - "27036:27017"
    volumes_from:
    - mongodata
    # command: --smallfiles --rest --auth   # this commad make sure that we access mongdodb with username and password!

  mongodata:    
    image: mongo 
    # image: tianon/true 
    volumes:
    # currently we mound the DB to ./data/db but we can also mount it to /private/data/db. Before we mount it there we must make sure that 
    # the folder /data/db was created ahead due to permissions issues.
    - ./data/db:/data/db  #mount the mongoDB files to the localfile system    
    command: 
      - --break-mongo
```

#### Logs/Trace

Logs from the browser.
Didn't saw any errors on docker

```
dashboard.bundle.js:47930 Warning: Automatically setting basename using <base href> is deprecated and will be removed in the next major release. The semantics of <base href> are subtly different from basename. Please pass the basename explicitly in the options to createHistory
warning @ dashboard.bundle.js:47930
dashboard.bundle.js:47073 Warning: [react-router] You cannot change <Router routes>; it will be ignored
```

Thanks in advanced for any help.
